-- premake5 script generated by 2pake
workspace "CLib"

configurations { "debug" }
configurations { "release" }
platforms { "linux" }

	filter { "configurations:debug" }
		defines { "DEBUG" }
		runtime "Debug"

	filter { "configurations:release" }
		defines { "RELEASE" }
		runtime "Release"
		optimize "On"

	filter { "platforms:linux" }
		defines { "LINUX" }
		system "linux"

project "So"
	language "C"
	kind "SharedLib"
	targetdir "bin/%{cfg.buildcfg}_%{cfg.system}"

	files { "src/**.c", "src/**.h"}

includedirs
{
	"src"
}
